In [1]:
import numpy as np
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [2]:
print(np.zeros((5,6)))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [3]:
print(np.ones((5,6)))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [4]:
x=np.arange(30).reshape(5,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [5]:
#random number generation
import numpy as np
#RAND
np.random.seed(6)
print(np.random.rand(10,6))
# always gonna have +ve value and value is always less than 1, t follows pattern we can got same value for the same number only if we give seed number

[[0.89286015 0.33197981 0.82122912 0.04169663 0.10765668 0.59505206]
 [0.52981736 0.41880743 0.33540785 0.62251943 0.43814143 0.73588211]
 [0.51803641 0.5788586  0.6453551  0.99022427 0.8198582  0.41320093]
 [0.87626766 0.82375943 0.05447451 0.71863724 0.80217056 0.73640664]
 [0.70913175 0.54093685 0.12482417 0.9576473  0.4032563  0.21695116]
 [0.71727585 0.99420744 0.25561406 0.67130943 0.59900591 0.71733215]
 [0.93734953 0.35180977 0.2536341  0.40247251 0.74651072 0.72407057]
 [0.4061078  0.98937985 0.45049928 0.37380843 0.70962861 0.08245855]
 [0.39837292 0.77088097 0.76475098 0.28385938 0.18954219 0.47125096]
 [0.33480604 0.73473504 0.18910712 0.33110407 0.84422842 0.61502403]]


In [6]:
#randn
print(np.random.randn(10,3))
#can have -ve,+ve number, values can be -1 to +1, mean gonna be very near to 0 and below, gonna have graph in shape of bell

[[-0.37550472  0.39636757 -0.47144628]
 [ 2.33660781  1.50278553 -0.59545972]
 [ 0.52834106  0.9398248   0.42628539]
 [-0.75815703 -0.16236698  0.72680996]
 [ 0.44408297 -0.85682264  0.44692842]
 [-1.01464799 -2.1323234   0.17386307]
 [ 0.95120126  0.44189739  1.46901739]
 [ 1.74951635  0.35353062 -0.64333729]
 [-0.04723705 -1.44903979 -0.03618977]
 [-0.09084699  0.17629034  1.09462041]]


In [7]:
#randint
print(np.random.randint(5,20,100))


[12 12 16 10  8 13 12  8 15 10 14  8 13  5 12 17 12 18  5  8 10  8 18  7
 17  8 19  9 18 18 14  5 13 11 19  8  7  6 11 13 13 14  5 12 11  5  6 13
 10 19 14 17 13 18 10 14 17  6 17  6  7 14 14 10 16 11  9 15  5  9  7 11
  7 17  6 19 17 19 15 14  7  5 16  7  7 15 10  5 12 17 16 11 11 15  5 14
 10 18 19  9]


In [8]:
print(np.random.randint(1,30,(9,7)))


[[27 25  3 28 21  3  4]
 [12 10  5 15 17  6 27]
 [ 8 23  2  2 24  2  7]
 [27 25  2  6 10 29 14]
 [ 3 19 12 21 11 27  9]
 [ 8  2 22  4 21  7  5]
 [22  7  9 22 10 24 28]
 [ 1  4 21 23 29  3  8]
 [16 23  1  6 15 15 25]]


In [9]:
#numpy condition
#below are the employee salary
emp_salary=np.random.randint(8,70,10)
emp_salary

array([37, 68, 48, 50, 66, 32, 14, 41, 54, 13])

In [10]:
#set max and min salary
np.clip(emp_salary,a_min = 20,a_max=50)

array([37, 50, 48, 50, 50, 32, 20, 41, 50, 20])

In [11]:
#if you want to find out actuallly salary which are less than or greater than some salary use np.where
#np.where gives index details
print(np.where(emp_salary <20))

(array([6, 9], dtype=int64),)


In [12]:
#if you want to see actual data use index
emp_salary[[0,2,4]]

array([37, 48, 66])

In [13]:
#reshapping in other ways
import numpy as np
from numpy.random import randint as ri
a=ri(1,99,30)
a

array([12, 43, 12, 45,  2,  8,  8, 97, 70, 64,  6,  9, 46, 75,  4, 37, 40,
       67, 43, 23, 82, 51, 84, 84, 19, 78, 48, 66, 97, 70])

In [14]:
b=a.reshape(2,3,5)
b

array([[[12, 43, 12, 45,  2],
        [ 8,  8, 97, 70, 64],
        [ 6,  9, 46, 75,  4]],

       [[37, 40, 67, 43, 23],
        [82, 51, 84, 84, 19],
        [78, 48, 66, 97, 70]]])

In [15]:
c=a.reshape(6,5)
c

array([[12, 43, 12, 45,  2],
       [ 8,  8, 97, 70, 64],
       [ 6,  9, 46, 75,  4],
       [37, 40, 67, 43, 23],
       [82, 51, 84, 84, 19],
       [78, 48, 66, 97, 70]])

In [16]:
print('Min of a',c.min())
print('Max of b',c.max())

Min of a 2
Max of b 97


In [17]:
M=ri(1,100,25).reshape(5,5)
print(M)
print(np.sort(M))
print(np.sort(M,axis=0))

[[45 21 17 85 55]
 [50 73 83 85 20]
 [28  6 85 61  6]
 [16 38  7 28 80]
 [56 24 84 36  3]]
[[17 21 45 55 85]
 [20 50 73 83 85]
 [ 6  6 28 61 85]
 [ 7 16 28 38 80]
 [ 3 24 36 56 84]]
[[16  6  7 28  3]
 [28 21 17 36  6]
 [45 24 83 61 20]
 [50 38 84 85 55]
 [56 73 85 85 80]]


In [18]:
#index and slicing
arr=np.arange(13,30)
print(arr)

[13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [19]:
print(arr[7])

20


In [20]:
print(arr[3:6])

[16 17 18]


In [21]:
print(arr[4:])
abc=arr[4:]

[17 18 19 20 21 22 23 24 25 26 27 28 29]


In [22]:
abc

array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [23]:
arr

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
print(arr[-1::-2])

[29 27 25 23 21 19 17 15 13]


In [25]:
arr=np.arange(0,21,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [26]:
print(arr[[2,4,9]]) #to find the index

[ 4  8 18]


In [29]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
mat[1][2]

6

In [31]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
mat[2]

array([7, 8, 9])

In [33]:
mat[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [34]:
mat[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
mat[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [36]:
mat[1:2,1:2]

array([[5]])

In [37]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
print(mat[0:2,[1,2]])

[[2 3]
 [5 6]]


In [39]:
#update matrix
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
mat[0,1]=35
mat

array([[ 1, 35,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [41]:
mat[1,0]=100
mat

array([[  1,  35,   3],
       [100,   5,   6],
       [  7,   8,   9]])

In [42]:
#subseting
mat=np.array(ri(10,100,15)).reshape(3,5)
mat

array([[91, 64, 33, 73, 68],
       [29, 28, 81, 36, 67],
       [37, 30, 36, 90, 67]])

In [43]:
xyz=mat[mat>70]
xyz

array([91, 73, 81, 90])

In [44]:
xyz=mat[mat>50]
xyz

array([91, 64, 73, 68, 81, 67, 90, 67])

In [61]:
print(np.where(mat==91))

(array([0], dtype=int64), array([0], dtype=int64))


In [46]:
#universal functions
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)
mat1


array([[5, 1, 1],
       [5, 5, 4],
       [5, 5, 7]])

In [47]:
mat2

array([[8, 1, 6],
       [8, 6, 3],
       [2, 2, 2]])

In [48]:
print(mat1+mat2)

[[13  2  7]
 [13 11  7]
 [ 7  7  9]]


In [49]:
print(mat1*mat2)

[[40  1  6]
 [40 30 12]
 [10 10 14]]


In [50]:
print(mat1)
"/n"
print(mat2)

[[5 1 1]
 [5 5 4]
 [5 5 7]]
[[8 1 6]
 [8 6 3]
 [2 2 2]]


In [51]:
print(mat1/mat2)

[[0.625      1.         0.16666667]
 [0.625      0.83333333 1.33333333]
 [2.5        2.5        3.5       ]]


In [52]:
print(mat1*mat2)

[[40  1  6]
 [40 30 12]
 [10 10 14]]


In [53]:
#Broadcasting
start=np.zeros((3,3))
start

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
add_rows=np.array([[1,0,2]])
add_rows

array([[1, 0, 2]])

In [55]:
y=start+add_rows
y

array([[1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.]])

In [56]:
new_row=add_rows.T
new_row

array([[1],
       [0],
       [2]])

In [57]:
#Array math
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)
print(mat1)
print(mat2)

[[7 8 7]
 [5 4 2]
 [1 7 8]]
[[5 1 7]
 [3 4 2]
 [3 1 8]]


In [58]:
np.sqrt(mat1)

array([[2.64575131, 2.82842712, 2.64575131],
       [2.23606798, 2.        , 1.41421356],
       [1.        , 2.64575131, 2.82842712]])

In [59]:
np.square(mat1)

array([[49, 64, 49],
       [25, 16,  4],
       [ 1, 49, 64]], dtype=int32)

In [60]:
import numpy
print(dir(numpy))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp